spring.application.name=producto
server.port=8085
spring.datasource.url=jdbc:h2:mem:productodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar la consola web de H2
spring.h2.console.enabled=true

# Cambiar la ruta de acceso (Por defecto es /h2-console)
spring.h2.console.path=/h2-console